---

- name: Install default software
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - net-tools
    - nmap
    - ack


- name: install sshuttle
  pip:
    name: sshuttle
