---

- include_tasks: vagrant.yml

- name: Check if guest is VirtualBox
  stat:
    path: /root/.vbox_version
  register: is_virtualbox

- name: Check if guest additions are installed
  stat:
    path: /opt/VBoxGuestAdditions*
  register: has_vboxguestadditions

- include_tasks: virtualbox.yml
  when: is_virtualbox.stat.exists and not has_vboxguestadditions.stat.exists
